// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "rescript/lib/es6/array.js";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function make(baseUrlOpt) {
  var baseUrl = baseUrlOpt !== undefined ? baseUrlOpt : "http://localhost:4000";
  return {
          baseUrl: baseUrl
        };
}

function parseStatus(str) {
  switch (str) {
    case "degraded" :
    case "deploying" :
        return "Pending";
    case "healthy" :
        return "Running";
    case "not_deployed" :
        return "Stopped";
    default:
      return "Error";
  }
}

var Fetch = {};

function getString(dict, key) {
  var json = Js_dict.get(dict, key);
  if (json !== undefined) {
    return Js_json.decodeString(json);
  }
  
}

function getInt(dict, key) {
  var json = Js_dict.get(dict, key);
  if (json === undefined) {
    return ;
  }
  var num = Js_json.decodeNumber(json);
  if (num !== undefined) {
    return num | 0;
  }
  
}

function getBool(dict, key) {
  var json = Js_dict.get(dict, key);
  if (json !== undefined) {
    return Js_json.decodeBoolean(json);
  }
  
}

function getObject(dict, key) {
  var json = Js_dict.get(dict, key);
  if (json !== undefined) {
    return Js_json.decodeObject(json);
  }
  
}

function getArray(dict, key) {
  var json = Js_dict.get(dict, key);
  if (json !== undefined) {
    return Js_json.decodeArray(json);
  }
  
}

function moduleInfo(json) {
  var dict = Js_json.decodeObject(json);
  if (dict === undefined) {
    return {
            TAG: "Error",
            _0: "Expected object for module",
            [Symbol.for("name")]: "Error"
          };
  }
  var match = getObject(dict, "manifest");
  var match$1 = getString(dict, "status");
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "Missing required fields in module",
            [Symbol.for("name")]: "Error"
          };
  }
  if (match$1 === undefined) {
    return {
            TAG: "Error",
            _0: "Missing required fields in module",
            [Symbol.for("name")]: "Error"
          };
  }
  var match$2 = getString(match, "name");
  var match$3 = getString(match, "version");
  var match$4 = getString(match, "layer");
  if (match$2 !== undefined && match$3 !== undefined && match$4 !== undefined) {
    return {
            TAG: "Ok",
            _0: {
              name: match$2,
              status: parseStatus(match$1),
              completion: 100,
              layer: match$4,
              version: match$3
            },
            [Symbol.for("name")]: "Ok"
          };
  } else {
    return {
            TAG: "Error",
            _0: "Missing required manifest fields",
            [Symbol.for("name")]: "Error"
          };
  }
}

function moduleArray(json) {
  var dict = Js_json.decodeObject(json);
  if (dict === undefined) {
    return {
            TAG: "Error",
            _0: "Expected object with modules field",
            [Symbol.for("name")]: "Error"
          };
  }
  var modulesJson = getArray(dict, "modules");
  if (modulesJson === undefined) {
    return {
            TAG: "Error",
            _0: "Missing modules array",
            [Symbol.for("name")]: "Error"
          };
  }
  var decoded = $$Array.map(moduleInfo, modulesJson);
  var initialResult = {
    TAG: "Ok",
    _0: [],
    [Symbol.for("name")]: "Ok"
  };
  return $$Array.fold_left((function (acc, result) {
                if (acc.TAG === "Ok") {
                  if (result.TAG === "Ok") {
                    return {
                            TAG: "Ok",
                            _0: $$Array.append(acc._0, [result._0]),
                            [Symbol.for("name")]: "Ok"
                          };
                  } else {
                    return {
                            TAG: "Error",
                            _0: result._0,
                            [Symbol.for("name")]: "Error"
                          };
                  }
                } else {
                  return acc;
                }
              }), initialResult, decoded);
}

function healthSummary(json) {
  var dict = Js_json.decodeObject(json);
  if (dict === undefined) {
    return {
            TAG: "Error",
            _0: "Expected object with health field",
            [Symbol.for("name")]: "Error"
          };
  }
  var health = getObject(dict, "health");
  if (health === undefined) {
    return {
            TAG: "Error",
            _0: "Missing health object",
            [Symbol.for("name")]: "Error"
          };
  }
  var match = getBool(health, "allHealthy");
  var match$1 = getInt(health, "healthyCount");
  var match$2 = getInt(health, "unhealthyCount");
  var match$3 = getInt(health, "unknownCount");
  if (match !== undefined && match$1 !== undefined && match$2 !== undefined && match$3 !== undefined) {
    return {
            TAG: "Ok",
            _0: {
              allHealthy: match,
              healthyCount: match$1,
              unhealthyCount: match$2,
              unknownCount: match$3
            },
            [Symbol.for("name")]: "Ok"
          };
  } else {
    return {
            TAG: "Error",
            _0: "Missing required health fields",
            [Symbol.for("name")]: "Error"
          };
  }
}

function deploymentOrder(json) {
  var dict = Js_json.decodeObject(json);
  if (dict === undefined) {
    return {
            TAG: "Error",
            _0: "Expected object with order field",
            [Symbol.for("name")]: "Error"
          };
  }
  var orderJson = getArray(dict, "order");
  if (orderJson === undefined) {
    return {
            TAG: "Error",
            _0: "Missing order array",
            [Symbol.for("name")]: "Error"
          };
  }
  var decoded = $$Array.fold_left((function (acc, item) {
          var str = Js_json.decodeString(item);
          if (str !== undefined) {
            return $$Array.append(acc, [str]);
          } else {
            return acc;
          }
        }), [], orderJson);
  return {
          TAG: "Ok",
          _0: decoded,
          [Symbol.for("name")]: "Ok"
        };
}

function logsResponse(json) {
  var dict = Js_json.decodeObject(json);
  if (dict === undefined) {
    return {
            TAG: "Error",
            _0: "Expected object for logs response",
            [Symbol.for("name")]: "Error"
          };
  }
  var match = getString(dict, "module");
  var match$1 = getString(dict, "logs");
  if (match !== undefined && match$1 !== undefined) {
    return {
            TAG: "Ok",
            _0: {
              moduleName: match,
              logs: match$1
            },
            [Symbol.for("name")]: "Ok"
          };
  } else {
    return {
            TAG: "Error",
            _0: "Missing required logs fields",
            [Symbol.for("name")]: "Error"
          };
  }
}

var Decode = {
  getString: getString,
  getInt: getInt,
  getBool: getBool,
  getObject: getObject,
  getArray: getArray,
  moduleInfo: moduleInfo,
  moduleArray: moduleArray,
  healthSummary: healthSummary,
  deploymentOrder: deploymentOrder,
  logsResponse: logsResponse
};

async function fetchJson(url) {
  try {
    var response = await fetch(url);
    if (!response.ok) {
      return {
              TAG: "Error",
              _0: "HTTP " + String(response.status) + ": " + response.statusText,
              [Symbol.for("name")]: "Error"
            };
    }
    var json = await response.json();
    return {
            TAG: "Ok",
            _0: json,
            [Symbol.for("name")]: "Ok"
          };
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID === Js_exn.$$Error) {
      var msg = e._1.message;
      if (msg !== undefined) {
        return {
                TAG: "Error",
                _0: msg,
                [Symbol.for("name")]: "Error"
              };
      } else {
        return {
                TAG: "Error",
                _0: "Unknown fetch error",
                [Symbol.for("name")]: "Error"
              };
      }
    }
    throw e;
  }
}

async function postJson(url, body) {
  try {
    var headers = {};
    headers["Content-Type"] = "application/json";
    var init = body !== undefined ? ({
          method: "POST",
          headers: headers,
          body: JSON.stringify(body)
        }) : ({
          method: "POST",
          headers: headers
        });
    var response = await fetch(url, init);
    if (!response.ok) {
      return {
              TAG: "Error",
              _0: "HTTP " + String(response.status) + ": " + response.statusText,
              [Symbol.for("name")]: "Error"
            };
    }
    var json = await response.json();
    return {
            TAG: "Ok",
            _0: json,
            [Symbol.for("name")]: "Ok"
          };
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID === Js_exn.$$Error) {
      var msg = e._1.message;
      if (msg !== undefined) {
        return {
                TAG: "Error",
                _0: msg,
                [Symbol.for("name")]: "Error"
              };
      } else {
        return {
                TAG: "Error",
                _0: "Unknown POST error",
                [Symbol.for("name")]: "Error"
              };
      }
    }
    throw e;
  }
}

async function getModules(client) {
  var url = client.baseUrl + "/api/modules";
  var json = await fetchJson(url);
  if (json.TAG === "Ok") {
    return moduleArray(json._0);
  } else {
    return {
            TAG: "Error",
            _0: json._0,
            [Symbol.for("name")]: "Error"
          };
  }
}

async function getModule(client, name) {
  var url = client.baseUrl + "/api/modules/" + name;
  var json = await fetchJson(url);
  if (json.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: json._0,
            [Symbol.for("name")]: "Error"
          };
  }
  var dict = Js_json.decodeObject(json._0);
  if (dict === undefined) {
    return {
            TAG: "Error",
            _0: "Expected object with module field",
            [Symbol.for("name")]: "Error"
          };
  }
  var moduleObj = getObject(dict, "module");
  if (moduleObj !== undefined) {
    return moduleInfo(moduleObj);
  } else {
    return {
            TAG: "Error",
            _0: "Missing module field",
            [Symbol.for("name")]: "Error"
          };
  }
}

async function getHealth(client) {
  var url = client.baseUrl + "/api/health";
  var json = await fetchJson(url);
  if (json.TAG === "Ok") {
    return healthSummary(json._0);
  } else {
    return {
            TAG: "Error",
            _0: json._0,
            [Symbol.for("name")]: "Error"
          };
  }
}

async function getDeploymentOrder(client) {
  var url = client.baseUrl + "/api/deployment_order";
  var json = await fetchJson(url);
  if (json.TAG === "Ok") {
    return deploymentOrder(json._0);
  } else {
    return {
            TAG: "Error",
            _0: json._0,
            [Symbol.for("name")]: "Error"
          };
  }
}

async function deployAll(client) {
  var url = client.baseUrl + "/api/deploy";
  var _json = await postJson(url, undefined);
  if (_json.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              status: "deployment_initiated",
              message: "All modules deployment started",
              moduleName: undefined
            },
            [Symbol.for("name")]: "Ok"
          };
  } else {
    return {
            TAG: "Error",
            _0: _json._0,
            [Symbol.for("name")]: "Error"
          };
  }
}

async function deployModule(client, name) {
  var url = client.baseUrl + "/api/deploy/" + name;
  var _json = await postJson(url, undefined);
  if (_json.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              status: "deployment_initiated",
              message: undefined,
              moduleName: name
            },
            [Symbol.for("name")]: "Ok"
          };
  } else {
    return {
            TAG: "Error",
            _0: _json._0,
            [Symbol.for("name")]: "Error"
          };
  }
}

async function restartModule(client, name) {
  var url = client.baseUrl + "/api/restart/" + name;
  var _json = await postJson(url, undefined);
  if (_json.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              status: "restart_initiated",
              message: undefined,
              moduleName: name
            },
            [Symbol.for("name")]: "Ok"
          };
  } else {
    return {
            TAG: "Error",
            _0: _json._0,
            [Symbol.for("name")]: "Error"
          };
  }
}

async function stopModule(client, name) {
  var url = client.baseUrl + "/api/stop/" + name;
  var _json = await postJson(url, undefined);
  if (_json.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              status: "stop_initiated",
              message: undefined,
              moduleName: name
            },
            [Symbol.for("name")]: "Ok"
          };
  } else {
    return {
            TAG: "Error",
            _0: _json._0,
            [Symbol.for("name")]: "Error"
          };
  }
}

async function getLogs(client, name, linesOpt) {
  var lines = linesOpt !== undefined ? linesOpt : 50;
  var url = client.baseUrl + "/api/logs/" + name + "?lines=" + String(lines);
  var json = await fetchJson(url);
  if (json.TAG === "Ok") {
    return logsResponse(json._0);
  } else {
    return {
            TAG: "Error",
            _0: json._0,
            [Symbol.for("name")]: "Error"
          };
  }
}

export {
  make ,
  parseStatus ,
  Fetch ,
  Decode ,
  fetchJson ,
  postJson ,
  getModules ,
  getModule ,
  getHealth ,
  getDeploymentOrder ,
  deployAll ,
  deployModule ,
  restartModule ,
  stopModule ,
  getLogs ,
}
/* No side effect */
